### ISSUE TITLE
Error during download analysis-seunjeon-7.16.3.zip

### ISSUE THREAD

**Issue by robycuccurese** [likejazz/seunjeon-elasticsearch-7#2]
Hi,

I'm trying to download the zip related to the version 7.16.3 through this command:

bin/elasticsearch-plugin install https://github.com/likejazz/seunjeon-elasticsearch-7/releases/download/7.16.3/analysis-seunjeon-7.16.3.zip

and the download start but I'm obtaining this error:

Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream
        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
        at org.elasticsearch.plugins.InstallPluginCommand.unzip(InstallPluginCommand.java:738)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:244)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:80)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.Command.main(Command.java:79)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:36)

do you know how to resolve it?
Thanks

**Comment by javierrey** [comment]
Deleted my previous message because it's not related.
